### ISSUE TITLE
`cpr` submodule is specified as an SSH URI instead of HTTPS

### ISSUE THREAD

**Issue by Skirmisher** [blackle/Basilisk-Hunter#1]
This causes the submodule to fail if SSH credentials aren't configured for GitHub on the local machine. Doing a manual clone of `cpr` using HTTPS and then rerunning the submodule update was a suitable workaround.

Getting ~20 MH/s with 8 threads on my Nexus 6P 👀

**Comment by blackle** [comment]
oops I didn't notice this!

thankfully this is irrelevant now because I removed cpr. thanks for reporting anyway!
